### ISSUE TITLE
Using Logicsim3 on a CPLD (Complex Programmable Logic Device)

### ISSUE THREAD

**Issue by Arvedino** [codepiet/LogicSim3#10]
Can I use Logicsim3 to program a CPLD?

**Comment by codepiet** [comment]
Hi Arvedino,
I used LogicSim3 to simulate a real simple 8bit CPU (Ben Eater-Version) - this was a little demanding for the real CPU but worked.
LogicSim3 is not error-free. If the project of yours is challenging and is quite important, i would rather use a more professional tool. LogicSim3 is developed for school basically.
kind regars
peter

**Comment by Arvedino** [comment]
Oh ok thanks!
