### ISSUE TITLE
error "gate type 'and' not there"

### ISSUE THREAD

**Issue by chocolatepatty** [codepiet/LogicSim3#2]
Upon following instructions in "compiling.txt" as closely as possible, upon startup multiple readerrors are thrown (i.e. "error reading file (wrong LogicSim-version?): gate type 'and' not there", similarly for or).

The only components that appear in the left-hand toolbar are "FA" and "HA".

![Screenshot from 2020-04-17 16-26-49](https://user-images.githubusercontent.com/1360470/79586148-a5b2e280-80c8-11ea-893f-124dfeeca621.png)

Using OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu119.10.1) if that's any help

**Comment by codepiet** [comment]
Thanks for your report. You checked out the repository and tried to start the project?
I am developing with Eclipse. I think I'll have to check the compiling.txt file.
Unfortunately I tested LogicSim with Windows10 and MacOS Mojave. I will try LogicSim on the Raspberry tonight.
Did you try the release-Version in the Releases-Subdir?  Just unzip and start LogicSim.jar.
I am using OpenJDK, too.

**Comment by codepiet** [comment]
I just tested on raspberry pi. had an JNI Error about wrong class file version. Fixed the error in the ant build file. Added   javac target=1.8 and source=1.8 option.

But this is not the error that you experienced. Would you test again?
So checkout the zip file and run it.
I put the content from compiling txt into README...

**Comment by chocolatepatty** [comment]
Appreciate the speedy reply- still getting the error via the terminal but I've tried using eclipse and have got it working that way.

Would guess it's probably not worth too much sweat for the moment pinning it down any more than that- seems to work well enough to be able to tinker a bit, so I'll close the issue but will let you know if I can work out what was going wrong in terminal
